from app import db
from datetime import datetime

class Challenge(db.Model):
    __tablename__ = 'challenges'
    
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    type = db.Column(db.String(50))  # Strength, Core, Cardio, etc.
    duration = db.Column(db.String(50))  # "30 Days", "7 Days", etc.
    difficulty = db.Column(db.String(20))  # Beginner, Intermediate, Advanced
    goal = db.Column(db.String(50))  # Weight Loss, Strength, etc.
    description = db.Column(db.Text)
    is_ai_generated = db.Column(db.Boolean, default=False)  # True if generated by Gemini
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Relationships
    user_challenges = db.relationship('UserChallenge', backref='challenge', lazy=True, cascade='all, delete-orphan')

class UserChallenge(db.Model):
    __tablename__ = 'user_challenges'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    challenge_id = db.Column(db.Integer, db.ForeignKey('challenges.id'), nullable=False)
    joined_at = db.Column(db.DateTime, default=datetime.utcnow)
    progress_percentage = db.Column(db.Float, default=0.0)
    is_completed = db.Column(db.Boolean, default=False)
    completed_at = db.Column(db.DateTime, nullable=True)
    
    # Relationships
    progress_entries = db.relationship('ChallengeProgress', backref='user_challenge', lazy=True, cascade='all, delete-orphan')
    
    # Unique constraint: one user can only join a challenge once
    __table_args__ = (db.UniqueConstraint('user_id', 'challenge_id', name='unique_user_challenge'),)

class ChallengeProgress(db.Model):
    __tablename__ = 'challenge_progress'
    
    id = db.Column(db.Integer, primary_key=True)
    user_challenge_id = db.Column(db.Integer, db.ForeignKey('user_challenges.id'), nullable=False)
    progress_date = db.Column(db.Date, nullable=False)  # Date when progress was marked
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Unique constraint: one progress entry per day per challenge
    __table_args__ = (db.UniqueConstraint('user_challenge_id', 'progress_date', name='unique_daily_progress'),)

